[package]
name = "rshttp2"
version = "0.1.0"
authors = ["Taoda <tyf00@aliyun.com>"]
edition = "2018"

[dependencies]
tokio = "0.1"
tokio-sync = "0.1"
tokio-timer = "0.2"
futures = "0.1"
log = "0.4"
flexi_logger = "0.6"
random = "0.12"
