// Generated by gen_huffman_codes.py. Do NEVER edit it directly.
use std::pin::Pin;
use std::ptr::null;
use std::marker::PhantomPinned;

#[derive(Debug)]
pub struct Item {
    pub lsb: u32,
    pub bits: usize,
}

pub struct HuffmanTree {
    nodes: Vec<TreeNode>,
    pub root: *const TreeNode,
    _pin: PhantomPinned,
}

#[derive(Debug, Clone)]
pub enum Char {
    Normal(u8),
    EoS,
}

#[derive(Debug)]
pub enum TreeNode {
    Leaf(Char),
    Inner((*const TreeNode, *const TreeNode)),
}

unsafe fn set_node_children(
    node: &mut TreeNode,
    left: *const TreeNode,
    right: *const TreeNode,
) -> () {
    match node {
        TreeNode::Leaf(_) => unreachable!(),
        TreeNode::Inner((ref mut l, ref mut r)) => {
            *l = left;
            *r = right;
        }
    }
}


impl HuffmanTree {
    pub fn new() -> Pin<Box<HuffmanTree>> {
        let res = HuffmanTree{
            nodes: vec!(),
            root: null(),
            _pin: PhantomPinned,
        };
        let mut boxed = Box::pin(res);
        unsafe {
            let mut_ref: Pin<&mut Self> = Pin::as_mut(&mut boxed);
            let mut_ref = Pin::get_unchecked_mut(mut_ref);

            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(48)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(49)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(50)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(97)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(99)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(101)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(105)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(111)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(115)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(116)));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(32)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(37)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(45)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(46)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(47)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(51)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(52)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(53)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(54)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(55)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(56)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(57)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(61)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(65)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(95)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(98)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(100)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(102)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(103)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(104)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(108)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(109)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(110)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(112)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(114)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(117)));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(58)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(66)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(67)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(68)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(69)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(70)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(71)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(72)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(73)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(74)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(75)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(76)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(77)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(78)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(79)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(80)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(81)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(82)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(83)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(84)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(85)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(86)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(87)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(89)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(106)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(107)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(113)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(118)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(119)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(120)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(121)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(122)));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(38)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(42)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(44)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(59)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(88)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(90)));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(33)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(34)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(40)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(41)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(63)));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(39)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(43)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(124)));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(35)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(62)));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(0)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(36)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(64)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(91)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(93)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(126)));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(94)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(125)));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(60)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(96)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(123)));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(92)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(195)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(208)));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(128)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(130)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(131)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(162)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(184)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(194)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(224)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(226)));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(153)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(161)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(167)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(172)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(176)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(177)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(179)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(209)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(216)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(217)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(227)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(229)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(230)));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(129)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(132)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(133)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(134)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(136)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(146)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(154)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(156)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(160)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(163)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(164)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(169)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(170)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(173)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(178)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(181)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(185)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(186)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(187)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(189)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(190)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(196)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(198)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(228)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(232)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(233)));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(1)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(135)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(137)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(138)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(139)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(140)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(141)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(143)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(147)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(149)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(150)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(151)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(152)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(155)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(157)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(158)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(165)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(166)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(168)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(174)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(175)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(180)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(182)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(183)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(188)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(191)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(197)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(231)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(239)));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(9)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(142)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(144)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(145)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(148)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(159)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(171)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(206)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(215)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(225)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(236)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(237)));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(199)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(207)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(234)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(235)));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(192)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(193)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(200)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(201)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(202)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(205)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(210)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(213)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(218)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(219)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(238)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(240)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(242)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(243)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(255)));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(203)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(204)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(211)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(212)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(214)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(221)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(222)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(223)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(241)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(244)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(245)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(246)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(247)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(248)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(250)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(251)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(252)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(253)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(254)));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(2)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(3)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(4)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(5)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(6)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(7)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(8)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(11)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(12)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(14)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(15)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(16)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(17)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(18)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(19)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(20)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(21)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(23)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(24)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(25)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(26)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(27)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(28)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(29)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(30)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(31)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(127)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(220)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(249)));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Inner((null(), null())));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(10)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(13)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::Normal(22)));
            mut_ref.nodes.push(TreeNode::Leaf(Char::EoS));

            let root = mut_ref.nodes.as_mut_ptr();
            mut_ref.root = root;

            set_node_children(&mut *(root.add(0)), root.add(1), root.add(2));
            set_node_children(&mut *(root.add(1)), root.add(3), root.add(4));
            set_node_children(&mut *(root.add(2)), root.add(5), root.add(6));
            set_node_children(&mut *(root.add(3)), root.add(7), root.add(8));
            set_node_children(&mut *(root.add(4)), root.add(9), root.add(10));
            set_node_children(&mut *(root.add(5)), root.add(11), root.add(12));
            set_node_children(&mut *(root.add(6)), root.add(13), root.add(14));
            set_node_children(&mut *(root.add(7)), root.add(15), root.add(16));
            set_node_children(&mut *(root.add(8)), root.add(17), root.add(18));
            set_node_children(&mut *(root.add(9)), root.add(19), root.add(20));
            set_node_children(&mut *(root.add(10)), root.add(21), root.add(22));
            set_node_children(&mut *(root.add(11)), root.add(23), root.add(24));
            set_node_children(&mut *(root.add(12)), root.add(25), root.add(26));
            set_node_children(&mut *(root.add(13)), root.add(27), root.add(28));
            set_node_children(&mut *(root.add(14)), root.add(29), root.add(30));
            set_node_children(&mut *(root.add(15)), root.add(31), root.add(32));
            set_node_children(&mut *(root.add(16)), root.add(33), root.add(34));
            set_node_children(&mut *(root.add(17)), root.add(35), root.add(36));
            set_node_children(&mut *(root.add(18)), root.add(37), root.add(38));
            set_node_children(&mut *(root.add(19)), root.add(39), root.add(40));
            set_node_children(&mut *(root.add(20)), root.add(41), root.add(42));
            set_node_children(&mut *(root.add(21)), root.add(43), root.add(44));
            set_node_children(&mut *(root.add(22)), root.add(45), root.add(46));
            set_node_children(&mut *(root.add(23)), root.add(47), root.add(48));
            set_node_children(&mut *(root.add(24)), root.add(49), root.add(50));
            set_node_children(&mut *(root.add(25)), root.add(51), root.add(52));
            set_node_children(&mut *(root.add(26)), root.add(53), root.add(54));
            set_node_children(&mut *(root.add(27)), root.add(55), root.add(56));
            set_node_children(&mut *(root.add(28)), root.add(57), root.add(58));
            set_node_children(&mut *(root.add(29)), root.add(59), root.add(60));
            set_node_children(&mut *(root.add(30)), root.add(61), root.add(62));
            set_node_children(&mut *(root.add(41)), root.add(63), root.add(64));
            set_node_children(&mut *(root.add(42)), root.add(65), root.add(66));
            set_node_children(&mut *(root.add(43)), root.add(67), root.add(68));
            set_node_children(&mut *(root.add(44)), root.add(69), root.add(70));
            set_node_children(&mut *(root.add(45)), root.add(71), root.add(72));
            set_node_children(&mut *(root.add(46)), root.add(73), root.add(74));
            set_node_children(&mut *(root.add(47)), root.add(75), root.add(76));
            set_node_children(&mut *(root.add(48)), root.add(77), root.add(78));
            set_node_children(&mut *(root.add(49)), root.add(79), root.add(80));
            set_node_children(&mut *(root.add(50)), root.add(81), root.add(82));
            set_node_children(&mut *(root.add(51)), root.add(83), root.add(84));
            set_node_children(&mut *(root.add(52)), root.add(85), root.add(86));
            set_node_children(&mut *(root.add(53)), root.add(87), root.add(88));
            set_node_children(&mut *(root.add(54)), root.add(89), root.add(90));
            set_node_children(&mut *(root.add(55)), root.add(91), root.add(92));
            set_node_children(&mut *(root.add(56)), root.add(93), root.add(94));
            set_node_children(&mut *(root.add(57)), root.add(95), root.add(96));
            set_node_children(&mut *(root.add(58)), root.add(97), root.add(98));
            set_node_children(&mut *(root.add(59)), root.add(99), root.add(100));
            set_node_children(&mut *(root.add(60)), root.add(101), root.add(102));
            set_node_children(&mut *(root.add(61)), root.add(103), root.add(104));
            set_node_children(&mut *(root.add(62)), root.add(105), root.add(106));
            set_node_children(&mut *(root.add(89)), root.add(107), root.add(108));
            set_node_children(&mut *(root.add(90)), root.add(109), root.add(110));
            set_node_children(&mut *(root.add(91)), root.add(111), root.add(112));
            set_node_children(&mut *(root.add(92)), root.add(113), root.add(114));
            set_node_children(&mut *(root.add(93)), root.add(115), root.add(116));
            set_node_children(&mut *(root.add(94)), root.add(117), root.add(118));
            set_node_children(&mut *(root.add(95)), root.add(119), root.add(120));
            set_node_children(&mut *(root.add(96)), root.add(121), root.add(122));
            set_node_children(&mut *(root.add(97)), root.add(123), root.add(124));
            set_node_children(&mut *(root.add(98)), root.add(125), root.add(126));
            set_node_children(&mut *(root.add(99)), root.add(127), root.add(128));
            set_node_children(&mut *(root.add(100)), root.add(129), root.add(130));
            set_node_children(&mut *(root.add(101)), root.add(131), root.add(132));
            set_node_children(&mut *(root.add(102)), root.add(133), root.add(134));
            set_node_children(&mut *(root.add(103)), root.add(135), root.add(136));
            set_node_children(&mut *(root.add(104)), root.add(137), root.add(138));
            set_node_children(&mut *(root.add(105)), root.add(139), root.add(140));
            set_node_children(&mut *(root.add(106)), root.add(141), root.add(142));
            set_node_children(&mut *(root.add(139)), root.add(143), root.add(144));
            set_node_children(&mut *(root.add(140)), root.add(145), root.add(146));
            set_node_children(&mut *(root.add(141)), root.add(147), root.add(148));
            set_node_children(&mut *(root.add(142)), root.add(149), root.add(150));
            set_node_children(&mut *(root.add(149)), root.add(151), root.add(152));
            set_node_children(&mut *(root.add(150)), root.add(153), root.add(154));
            set_node_children(&mut *(root.add(151)), root.add(155), root.add(156));
            set_node_children(&mut *(root.add(152)), root.add(157), root.add(158));
            set_node_children(&mut *(root.add(153)), root.add(159), root.add(160));
            set_node_children(&mut *(root.add(154)), root.add(161), root.add(162));
            set_node_children(&mut *(root.add(160)), root.add(163), root.add(164));
            set_node_children(&mut *(root.add(161)), root.add(165), root.add(166));
            set_node_children(&mut *(root.add(162)), root.add(167), root.add(168));
            set_node_children(&mut *(root.add(166)), root.add(169), root.add(170));
            set_node_children(&mut *(root.add(167)), root.add(171), root.add(172));
            set_node_children(&mut *(root.add(168)), root.add(173), root.add(174));
            set_node_children(&mut *(root.add(171)), root.add(175), root.add(176));
            set_node_children(&mut *(root.add(172)), root.add(177), root.add(178));
            set_node_children(&mut *(root.add(173)), root.add(179), root.add(180));
            set_node_children(&mut *(root.add(174)), root.add(181), root.add(182));
            set_node_children(&mut *(root.add(181)), root.add(183), root.add(184));
            set_node_children(&mut *(root.add(182)), root.add(185), root.add(186));
            set_node_children(&mut *(root.add(185)), root.add(187), root.add(188));
            set_node_children(&mut *(root.add(186)), root.add(189), root.add(190));
            set_node_children(&mut *(root.add(190)), root.add(191), root.add(192));
            set_node_children(&mut *(root.add(191)), root.add(193), root.add(194));
            set_node_children(&mut *(root.add(192)), root.add(195), root.add(196));
            set_node_children(&mut *(root.add(193)), root.add(197), root.add(198));
            set_node_children(&mut *(root.add(194)), root.add(199), root.add(200));
            set_node_children(&mut *(root.add(195)), root.add(201), root.add(202));
            set_node_children(&mut *(root.add(196)), root.add(203), root.add(204));
            set_node_children(&mut *(root.add(197)), root.add(205), root.add(206));
            set_node_children(&mut *(root.add(198)), root.add(207), root.add(208));
            set_node_children(&mut *(root.add(199)), root.add(209), root.add(210));
            set_node_children(&mut *(root.add(200)), root.add(211), root.add(212));
            set_node_children(&mut *(root.add(201)), root.add(213), root.add(214));
            set_node_children(&mut *(root.add(202)), root.add(215), root.add(216));
            set_node_children(&mut *(root.add(203)), root.add(217), root.add(218));
            set_node_children(&mut *(root.add(204)), root.add(219), root.add(220));
            set_node_children(&mut *(root.add(208)), root.add(221), root.add(222));
            set_node_children(&mut *(root.add(209)), root.add(223), root.add(224));
            set_node_children(&mut *(root.add(210)), root.add(225), root.add(226));
            set_node_children(&mut *(root.add(211)), root.add(227), root.add(228));
            set_node_children(&mut *(root.add(212)), root.add(229), root.add(230));
            set_node_children(&mut *(root.add(213)), root.add(231), root.add(232));
            set_node_children(&mut *(root.add(214)), root.add(233), root.add(234));
            set_node_children(&mut *(root.add(215)), root.add(235), root.add(236));
            set_node_children(&mut *(root.add(216)), root.add(237), root.add(238));
            set_node_children(&mut *(root.add(217)), root.add(239), root.add(240));
            set_node_children(&mut *(root.add(218)), root.add(241), root.add(242));
            set_node_children(&mut *(root.add(219)), root.add(243), root.add(244));
            set_node_children(&mut *(root.add(220)), root.add(245), root.add(246));
            set_node_children(&mut *(root.add(229)), root.add(247), root.add(248));
            set_node_children(&mut *(root.add(230)), root.add(249), root.add(250));
            set_node_children(&mut *(root.add(231)), root.add(251), root.add(252));
            set_node_children(&mut *(root.add(232)), root.add(253), root.add(254));
            set_node_children(&mut *(root.add(233)), root.add(255), root.add(256));
            set_node_children(&mut *(root.add(234)), root.add(257), root.add(258));
            set_node_children(&mut *(root.add(235)), root.add(259), root.add(260));
            set_node_children(&mut *(root.add(236)), root.add(261), root.add(262));
            set_node_children(&mut *(root.add(237)), root.add(263), root.add(264));
            set_node_children(&mut *(root.add(238)), root.add(265), root.add(266));
            set_node_children(&mut *(root.add(239)), root.add(267), root.add(268));
            set_node_children(&mut *(root.add(240)), root.add(269), root.add(270));
            set_node_children(&mut *(root.add(241)), root.add(271), root.add(272));
            set_node_children(&mut *(root.add(242)), root.add(273), root.add(274));
            set_node_children(&mut *(root.add(243)), root.add(275), root.add(276));
            set_node_children(&mut *(root.add(244)), root.add(277), root.add(278));
            set_node_children(&mut *(root.add(245)), root.add(279), root.add(280));
            set_node_children(&mut *(root.add(246)), root.add(281), root.add(282));
            set_node_children(&mut *(root.add(260)), root.add(283), root.add(284));
            set_node_children(&mut *(root.add(261)), root.add(285), root.add(286));
            set_node_children(&mut *(root.add(262)), root.add(287), root.add(288));
            set_node_children(&mut *(root.add(263)), root.add(289), root.add(290));
            set_node_children(&mut *(root.add(264)), root.add(291), root.add(292));
            set_node_children(&mut *(root.add(265)), root.add(293), root.add(294));
            set_node_children(&mut *(root.add(266)), root.add(295), root.add(296));
            set_node_children(&mut *(root.add(267)), root.add(297), root.add(298));
            set_node_children(&mut *(root.add(268)), root.add(299), root.add(300));
            set_node_children(&mut *(root.add(269)), root.add(301), root.add(302));
            set_node_children(&mut *(root.add(270)), root.add(303), root.add(304));
            set_node_children(&mut *(root.add(271)), root.add(305), root.add(306));
            set_node_children(&mut *(root.add(272)), root.add(307), root.add(308));
            set_node_children(&mut *(root.add(273)), root.add(309), root.add(310));
            set_node_children(&mut *(root.add(274)), root.add(311), root.add(312));
            set_node_children(&mut *(root.add(275)), root.add(313), root.add(314));
            set_node_children(&mut *(root.add(276)), root.add(315), root.add(316));
            set_node_children(&mut *(root.add(277)), root.add(317), root.add(318));
            set_node_children(&mut *(root.add(278)), root.add(319), root.add(320));
            set_node_children(&mut *(root.add(279)), root.add(321), root.add(322));
            set_node_children(&mut *(root.add(280)), root.add(323), root.add(324));
            set_node_children(&mut *(root.add(281)), root.add(325), root.add(326));
            set_node_children(&mut *(root.add(282)), root.add(327), root.add(328));
            set_node_children(&mut *(root.add(309)), root.add(329), root.add(330));
            set_node_children(&mut *(root.add(310)), root.add(331), root.add(332));
            set_node_children(&mut *(root.add(311)), root.add(333), root.add(334));
            set_node_children(&mut *(root.add(312)), root.add(335), root.add(336));
            set_node_children(&mut *(root.add(313)), root.add(337), root.add(338));
            set_node_children(&mut *(root.add(314)), root.add(339), root.add(340));
            set_node_children(&mut *(root.add(315)), root.add(341), root.add(342));
            set_node_children(&mut *(root.add(316)), root.add(343), root.add(344));
            set_node_children(&mut *(root.add(317)), root.add(345), root.add(346));
            set_node_children(&mut *(root.add(318)), root.add(347), root.add(348));
            set_node_children(&mut *(root.add(319)), root.add(349), root.add(350));
            set_node_children(&mut *(root.add(320)), root.add(351), root.add(352));
            set_node_children(&mut *(root.add(321)), root.add(353), root.add(354));
            set_node_children(&mut *(root.add(322)), root.add(355), root.add(356));
            set_node_children(&mut *(root.add(323)), root.add(357), root.add(358));
            set_node_children(&mut *(root.add(324)), root.add(359), root.add(360));
            set_node_children(&mut *(root.add(325)), root.add(361), root.add(362));
            set_node_children(&mut *(root.add(326)), root.add(363), root.add(364));
            set_node_children(&mut *(root.add(327)), root.add(365), root.add(366));
            set_node_children(&mut *(root.add(328)), root.add(367), root.add(368));
            set_node_children(&mut *(root.add(358)), root.add(369), root.add(370));
            set_node_children(&mut *(root.add(359)), root.add(371), root.add(372));
            set_node_children(&mut *(root.add(360)), root.add(373), root.add(374));
            set_node_children(&mut *(root.add(361)), root.add(375), root.add(376));
            set_node_children(&mut *(root.add(362)), root.add(377), root.add(378));
            set_node_children(&mut *(root.add(363)), root.add(379), root.add(380));
            set_node_children(&mut *(root.add(364)), root.add(381), root.add(382));
            set_node_children(&mut *(root.add(365)), root.add(383), root.add(384));
            set_node_children(&mut *(root.add(366)), root.add(385), root.add(386));
            set_node_children(&mut *(root.add(367)), root.add(387), root.add(388));
            set_node_children(&mut *(root.add(368)), root.add(389), root.add(390));
            set_node_children(&mut *(root.add(381)), root.add(391), root.add(392));
            set_node_children(&mut *(root.add(382)), root.add(393), root.add(394));
            set_node_children(&mut *(root.add(383)), root.add(395), root.add(396));
            set_node_children(&mut *(root.add(384)), root.add(397), root.add(398));
            set_node_children(&mut *(root.add(385)), root.add(399), root.add(400));
            set_node_children(&mut *(root.add(386)), root.add(401), root.add(402));
            set_node_children(&mut *(root.add(387)), root.add(403), root.add(404));
            set_node_children(&mut *(root.add(388)), root.add(405), root.add(406));
            set_node_children(&mut *(root.add(389)), root.add(407), root.add(408));
            set_node_children(&mut *(root.add(390)), root.add(409), root.add(410));
            set_node_children(&mut *(root.add(395)), root.add(411), root.add(412));
            set_node_children(&mut *(root.add(396)), root.add(413), root.add(414));
            set_node_children(&mut *(root.add(397)), root.add(415), root.add(416));
            set_node_children(&mut *(root.add(398)), root.add(417), root.add(418));
            set_node_children(&mut *(root.add(399)), root.add(419), root.add(420));
            set_node_children(&mut *(root.add(400)), root.add(421), root.add(422));
            set_node_children(&mut *(root.add(401)), root.add(423), root.add(424));
            set_node_children(&mut *(root.add(402)), root.add(425), root.add(426));
            set_node_children(&mut *(root.add(403)), root.add(427), root.add(428));
            set_node_children(&mut *(root.add(404)), root.add(429), root.add(430));
            set_node_children(&mut *(root.add(405)), root.add(431), root.add(432));
            set_node_children(&mut *(root.add(406)), root.add(433), root.add(434));
            set_node_children(&mut *(root.add(407)), root.add(435), root.add(436));
            set_node_children(&mut *(root.add(408)), root.add(437), root.add(438));
            set_node_children(&mut *(root.add(409)), root.add(439), root.add(440));
            set_node_children(&mut *(root.add(410)), root.add(441), root.add(442));
            set_node_children(&mut *(root.add(426)), root.add(443), root.add(444));
            set_node_children(&mut *(root.add(427)), root.add(445), root.add(446));
            set_node_children(&mut *(root.add(428)), root.add(447), root.add(448));
            set_node_children(&mut *(root.add(429)), root.add(449), root.add(450));
            set_node_children(&mut *(root.add(430)), root.add(451), root.add(452));
            set_node_children(&mut *(root.add(431)), root.add(453), root.add(454));
            set_node_children(&mut *(root.add(432)), root.add(455), root.add(456));
            set_node_children(&mut *(root.add(433)), root.add(457), root.add(458));
            set_node_children(&mut *(root.add(434)), root.add(459), root.add(460));
            set_node_children(&mut *(root.add(435)), root.add(461), root.add(462));
            set_node_children(&mut *(root.add(436)), root.add(463), root.add(464));
            set_node_children(&mut *(root.add(437)), root.add(465), root.add(466));
            set_node_children(&mut *(root.add(438)), root.add(467), root.add(468));
            set_node_children(&mut *(root.add(439)), root.add(469), root.add(470));
            set_node_children(&mut *(root.add(440)), root.add(471), root.add(472));
            set_node_children(&mut *(root.add(441)), root.add(473), root.add(474));
            set_node_children(&mut *(root.add(442)), root.add(475), root.add(476));
            set_node_children(&mut *(root.add(462)), root.add(477), root.add(478));
            set_node_children(&mut *(root.add(463)), root.add(479), root.add(480));
            set_node_children(&mut *(root.add(464)), root.add(481), root.add(482));
            set_node_children(&mut *(root.add(465)), root.add(483), root.add(484));
            set_node_children(&mut *(root.add(466)), root.add(485), root.add(486));
            set_node_children(&mut *(root.add(467)), root.add(487), root.add(488));
            set_node_children(&mut *(root.add(468)), root.add(489), root.add(490));
            set_node_children(&mut *(root.add(469)), root.add(491), root.add(492));
            set_node_children(&mut *(root.add(470)), root.add(493), root.add(494));
            set_node_children(&mut *(root.add(471)), root.add(495), root.add(496));
            set_node_children(&mut *(root.add(472)), root.add(497), root.add(498));
            set_node_children(&mut *(root.add(473)), root.add(499), root.add(500));
            set_node_children(&mut *(root.add(474)), root.add(501), root.add(502));
            set_node_children(&mut *(root.add(475)), root.add(503), root.add(504));
            set_node_children(&mut *(root.add(476)), root.add(505), root.add(506));
            set_node_children(&mut *(root.add(506)), root.add(507), root.add(508));
            set_node_children(&mut *(root.add(507)), root.add(509), root.add(510));
            set_node_children(&mut *(root.add(508)), root.add(511), root.add(512));
        }
        boxed
    }
}

pub const RAW_TABLE: [Item; 256] = [
    Item{lsb: 0x1ff8, bits: 13},
    Item{lsb: 0x7fffd8, bits: 23},
    Item{lsb: 0xfffffe2, bits: 28},
    Item{lsb: 0xfffffe3, bits: 28},
    Item{lsb: 0xfffffe4, bits: 28},
    Item{lsb: 0xfffffe5, bits: 28},
    Item{lsb: 0xfffffe6, bits: 28},
    Item{lsb: 0xfffffe7, bits: 28},
    Item{lsb: 0xfffffe8, bits: 28},
    Item{lsb: 0xffffea, bits: 24},
    Item{lsb: 0x3ffffffc, bits: 30},
    Item{lsb: 0xfffffe9, bits: 28},
    Item{lsb: 0xfffffea, bits: 28},
    Item{lsb: 0x3ffffffd, bits: 30},
    Item{lsb: 0xfffffeb, bits: 28},
    Item{lsb: 0xfffffec, bits: 28},
    Item{lsb: 0xfffffed, bits: 28},
    Item{lsb: 0xfffffee, bits: 28},
    Item{lsb: 0xfffffef, bits: 28},
    Item{lsb: 0xffffff0, bits: 28},
    Item{lsb: 0xffffff1, bits: 28},
    Item{lsb: 0xffffff2, bits: 28},
    Item{lsb: 0x3ffffffe, bits: 30},
    Item{lsb: 0xffffff3, bits: 28},
    Item{lsb: 0xffffff4, bits: 28},
    Item{lsb: 0xffffff5, bits: 28},
    Item{lsb: 0xffffff6, bits: 28},
    Item{lsb: 0xffffff7, bits: 28},
    Item{lsb: 0xffffff8, bits: 28},
    Item{lsb: 0xffffff9, bits: 28},
    Item{lsb: 0xffffffa, bits: 28},
    Item{lsb: 0xffffffb, bits: 28},
    Item{lsb: 0x14, bits: 6},
    Item{lsb: 0x3f8, bits: 10},
    Item{lsb: 0x3f9, bits: 10},
    Item{lsb: 0xffa, bits: 12},
    Item{lsb: 0x1ff9, bits: 13},
    Item{lsb: 0x15, bits: 6},
    Item{lsb: 0xf8, bits: 8},
    Item{lsb: 0x7fa, bits: 11},
    Item{lsb: 0x3fa, bits: 10},
    Item{lsb: 0x3fb, bits: 10},
    Item{lsb: 0xf9, bits: 8},
    Item{lsb: 0x7fb, bits: 11},
    Item{lsb: 0xfa, bits: 8},
    Item{lsb: 0x16, bits: 6},
    Item{lsb: 0x17, bits: 6},
    Item{lsb: 0x18, bits: 6},
    Item{lsb: 0x0, bits: 5},
    Item{lsb: 0x1, bits: 5},
    Item{lsb: 0x2, bits: 5},
    Item{lsb: 0x19, bits: 6},
    Item{lsb: 0x1a, bits: 6},
    Item{lsb: 0x1b, bits: 6},
    Item{lsb: 0x1c, bits: 6},
    Item{lsb: 0x1d, bits: 6},
    Item{lsb: 0x1e, bits: 6},
    Item{lsb: 0x1f, bits: 6},
    Item{lsb: 0x5c, bits: 7},
    Item{lsb: 0xfb, bits: 8},
    Item{lsb: 0x7ffc, bits: 15},
    Item{lsb: 0x20, bits: 6},
    Item{lsb: 0xffb, bits: 12},
    Item{lsb: 0x3fc, bits: 10},
    Item{lsb: 0x1ffa, bits: 13},
    Item{lsb: 0x21, bits: 6},
    Item{lsb: 0x5d, bits: 7},
    Item{lsb: 0x5e, bits: 7},
    Item{lsb: 0x5f, bits: 7},
    Item{lsb: 0x60, bits: 7},
    Item{lsb: 0x61, bits: 7},
    Item{lsb: 0x62, bits: 7},
    Item{lsb: 0x63, bits: 7},
    Item{lsb: 0x64, bits: 7},
    Item{lsb: 0x65, bits: 7},
    Item{lsb: 0x66, bits: 7},
    Item{lsb: 0x67, bits: 7},
    Item{lsb: 0x68, bits: 7},
    Item{lsb: 0x69, bits: 7},
    Item{lsb: 0x6a, bits: 7},
    Item{lsb: 0x6b, bits: 7},
    Item{lsb: 0x6c, bits: 7},
    Item{lsb: 0x6d, bits: 7},
    Item{lsb: 0x6e, bits: 7},
    Item{lsb: 0x6f, bits: 7},
    Item{lsb: 0x70, bits: 7},
    Item{lsb: 0x71, bits: 7},
    Item{lsb: 0x72, bits: 7},
    Item{lsb: 0xfc, bits: 8},
    Item{lsb: 0x73, bits: 7},
    Item{lsb: 0xfd, bits: 8},
    Item{lsb: 0x1ffb, bits: 13},
    Item{lsb: 0x7fff0, bits: 19},
    Item{lsb: 0x1ffc, bits: 13},
    Item{lsb: 0x3ffc, bits: 14},
    Item{lsb: 0x22, bits: 6},
    Item{lsb: 0x7ffd, bits: 15},
    Item{lsb: 0x3, bits: 5},
    Item{lsb: 0x23, bits: 6},
    Item{lsb: 0x4, bits: 5},
    Item{lsb: 0x24, bits: 6},
    Item{lsb: 0x5, bits: 5},
    Item{lsb: 0x25, bits: 6},
    Item{lsb: 0x26, bits: 6},
    Item{lsb: 0x27, bits: 6},
    Item{lsb: 0x6, bits: 5},
    Item{lsb: 0x74, bits: 7},
    Item{lsb: 0x75, bits: 7},
    Item{lsb: 0x28, bits: 6},
    Item{lsb: 0x29, bits: 6},
    Item{lsb: 0x2a, bits: 6},
    Item{lsb: 0x7, bits: 5},
    Item{lsb: 0x2b, bits: 6},
    Item{lsb: 0x76, bits: 7},
    Item{lsb: 0x2c, bits: 6},
    Item{lsb: 0x8, bits: 5},
    Item{lsb: 0x9, bits: 5},
    Item{lsb: 0x2d, bits: 6},
    Item{lsb: 0x77, bits: 7},
    Item{lsb: 0x78, bits: 7},
    Item{lsb: 0x79, bits: 7},
    Item{lsb: 0x7a, bits: 7},
    Item{lsb: 0x7b, bits: 7},
    Item{lsb: 0x7ffe, bits: 15},
    Item{lsb: 0x7fc, bits: 11},
    Item{lsb: 0x3ffd, bits: 14},
    Item{lsb: 0x1ffd, bits: 13},
    Item{lsb: 0xffffffc, bits: 28},
    Item{lsb: 0xfffe6, bits: 20},
    Item{lsb: 0x3fffd2, bits: 22},
    Item{lsb: 0xfffe7, bits: 20},
    Item{lsb: 0xfffe8, bits: 20},
    Item{lsb: 0x3fffd3, bits: 22},
    Item{lsb: 0x3fffd4, bits: 22},
    Item{lsb: 0x3fffd5, bits: 22},
    Item{lsb: 0x7fffd9, bits: 23},
    Item{lsb: 0x3fffd6, bits: 22},
    Item{lsb: 0x7fffda, bits: 23},
    Item{lsb: 0x7fffdb, bits: 23},
    Item{lsb: 0x7fffdc, bits: 23},
    Item{lsb: 0x7fffdd, bits: 23},
    Item{lsb: 0x7fffde, bits: 23},
    Item{lsb: 0xffffeb, bits: 24},
    Item{lsb: 0x7fffdf, bits: 23},
    Item{lsb: 0xffffec, bits: 24},
    Item{lsb: 0xffffed, bits: 24},
    Item{lsb: 0x3fffd7, bits: 22},
    Item{lsb: 0x7fffe0, bits: 23},
    Item{lsb: 0xffffee, bits: 24},
    Item{lsb: 0x7fffe1, bits: 23},
    Item{lsb: 0x7fffe2, bits: 23},
    Item{lsb: 0x7fffe3, bits: 23},
    Item{lsb: 0x7fffe4, bits: 23},
    Item{lsb: 0x1fffdc, bits: 21},
    Item{lsb: 0x3fffd8, bits: 22},
    Item{lsb: 0x7fffe5, bits: 23},
    Item{lsb: 0x3fffd9, bits: 22},
    Item{lsb: 0x7fffe6, bits: 23},
    Item{lsb: 0x7fffe7, bits: 23},
    Item{lsb: 0xffffef, bits: 24},
    Item{lsb: 0x3fffda, bits: 22},
    Item{lsb: 0x1fffdd, bits: 21},
    Item{lsb: 0xfffe9, bits: 20},
    Item{lsb: 0x3fffdb, bits: 22},
    Item{lsb: 0x3fffdc, bits: 22},
    Item{lsb: 0x7fffe8, bits: 23},
    Item{lsb: 0x7fffe9, bits: 23},
    Item{lsb: 0x1fffde, bits: 21},
    Item{lsb: 0x7fffea, bits: 23},
    Item{lsb: 0x3fffdd, bits: 22},
    Item{lsb: 0x3fffde, bits: 22},
    Item{lsb: 0xfffff0, bits: 24},
    Item{lsb: 0x1fffdf, bits: 21},
    Item{lsb: 0x3fffdf, bits: 22},
    Item{lsb: 0x7fffeb, bits: 23},
    Item{lsb: 0x7fffec, bits: 23},
    Item{lsb: 0x1fffe0, bits: 21},
    Item{lsb: 0x1fffe1, bits: 21},
    Item{lsb: 0x3fffe0, bits: 22},
    Item{lsb: 0x1fffe2, bits: 21},
    Item{lsb: 0x7fffed, bits: 23},
    Item{lsb: 0x3fffe1, bits: 22},
    Item{lsb: 0x7fffee, bits: 23},
    Item{lsb: 0x7fffef, bits: 23},
    Item{lsb: 0xfffea, bits: 20},
    Item{lsb: 0x3fffe2, bits: 22},
    Item{lsb: 0x3fffe3, bits: 22},
    Item{lsb: 0x3fffe4, bits: 22},
    Item{lsb: 0x7ffff0, bits: 23},
    Item{lsb: 0x3fffe5, bits: 22},
    Item{lsb: 0x3fffe6, bits: 22},
    Item{lsb: 0x7ffff1, bits: 23},
    Item{lsb: 0x3ffffe0, bits: 26},
    Item{lsb: 0x3ffffe1, bits: 26},
    Item{lsb: 0xfffeb, bits: 20},
    Item{lsb: 0x7fff1, bits: 19},
    Item{lsb: 0x3fffe7, bits: 22},
    Item{lsb: 0x7ffff2, bits: 23},
    Item{lsb: 0x3fffe8, bits: 22},
    Item{lsb: 0x1ffffec, bits: 25},
    Item{lsb: 0x3ffffe2, bits: 26},
    Item{lsb: 0x3ffffe3, bits: 26},
    Item{lsb: 0x3ffffe4, bits: 26},
    Item{lsb: 0x7ffffde, bits: 27},
    Item{lsb: 0x7ffffdf, bits: 27},
    Item{lsb: 0x3ffffe5, bits: 26},
    Item{lsb: 0xfffff1, bits: 24},
    Item{lsb: 0x1ffffed, bits: 25},
    Item{lsb: 0x7fff2, bits: 19},
    Item{lsb: 0x1fffe3, bits: 21},
    Item{lsb: 0x3ffffe6, bits: 26},
    Item{lsb: 0x7ffffe0, bits: 27},
    Item{lsb: 0x7ffffe1, bits: 27},
    Item{lsb: 0x3ffffe7, bits: 26},
    Item{lsb: 0x7ffffe2, bits: 27},
    Item{lsb: 0xfffff2, bits: 24},
    Item{lsb: 0x1fffe4, bits: 21},
    Item{lsb: 0x1fffe5, bits: 21},
    Item{lsb: 0x3ffffe8, bits: 26},
    Item{lsb: 0x3ffffe9, bits: 26},
    Item{lsb: 0xffffffd, bits: 28},
    Item{lsb: 0x7ffffe3, bits: 27},
    Item{lsb: 0x7ffffe4, bits: 27},
    Item{lsb: 0x7ffffe5, bits: 27},
    Item{lsb: 0xfffec, bits: 20},
    Item{lsb: 0xfffff3, bits: 24},
    Item{lsb: 0xfffed, bits: 20},
    Item{lsb: 0x1fffe6, bits: 21},
    Item{lsb: 0x3fffe9, bits: 22},
    Item{lsb: 0x1fffe7, bits: 21},
    Item{lsb: 0x1fffe8, bits: 21},
    Item{lsb: 0x7ffff3, bits: 23},
    Item{lsb: 0x3fffea, bits: 22},
    Item{lsb: 0x3fffeb, bits: 22},
    Item{lsb: 0x1ffffee, bits: 25},
    Item{lsb: 0x1ffffef, bits: 25},
    Item{lsb: 0xfffff4, bits: 24},
    Item{lsb: 0xfffff5, bits: 24},
    Item{lsb: 0x3ffffea, bits: 26},
    Item{lsb: 0x7ffff4, bits: 23},
    Item{lsb: 0x3ffffeb, bits: 26},
    Item{lsb: 0x7ffffe6, bits: 27},
    Item{lsb: 0x3ffffec, bits: 26},
    Item{lsb: 0x3ffffed, bits: 26},
    Item{lsb: 0x7ffffe7, bits: 27},
    Item{lsb: 0x7ffffe8, bits: 27},
    Item{lsb: 0x7ffffe9, bits: 27},
    Item{lsb: 0x7ffffea, bits: 27},
    Item{lsb: 0x7ffffeb, bits: 27},
    Item{lsb: 0xffffffe, bits: 28},
    Item{lsb: 0x7ffffec, bits: 27},
    Item{lsb: 0x7ffffed, bits: 27},
    Item{lsb: 0x7ffffee, bits: 27},
    Item{lsb: 0x7ffffef, bits: 27},
    Item{lsb: 0x7fffff0, bits: 27},
    Item{lsb: 0x3ffffee, bits: 26},
];

